### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by JoshDunnDev**
- Adds support for dark mode

Screen Shot 2019-10-01 at 11 33 23 AM

Screen Shot 2019-10-01 at 11 33 31 AM

Screen Shot 2019-10-01 at 11 33 49 AM

### CODE REVIEW

**Comment by dlongley** [comment]
The default `fa-globe` icon for origins without icons should be updated to use the white version when the user's preferred theme is dark.

**Comment by dlongley** [comment]
Can use something like this to detect dark mode in JS if necessary:

```js
if(window.matchMedia('(prefers-color-scheme: dark)')) {
    console.log ('dark mode is enabled');
}
```

**Comment by dlongley** [comment]
This site has some potentially useful tips on colorization to deal with favicon issues, etc.:

https://web.dev/prefers-color-scheme

**Comment by JoshDunnDev** [comment]
> Can use something like this to detect dark mode in JS if necessary:
> 
> ```js
> if(window.matchMedia('(prefers-color-scheme: dark)')) {
>     console.log ('dark mode is enabled');
> }
> ```
> 
> And this for catching changes:
> 
> ```js
> window.matchMedia('(prefers-color-scheme: dark)').addListener(function() {
>     console.log('changed to dark mode')
> });
> ```
> 
> Might need a computed property or something for the default icon based on the above.

I don't think this is needed because the CSS will understand the change. At least when I toggle dark mode off and on in Safari, there are no issues and no need for JS.

**Comment by JoshDunnDev** [comment]
Updated colors:

Screen Shot 2019-10-01 at 1 19 32 PM
Screen Shot 2019-10-01 at 1 19 44 PM
Screen Shot 2019-10-01 at 1 19 59 PM

**Comment by dlongley** [comment]
@JoshDunnDev,

> I don't think this is needed because the CSS will understand the change. At least when I toggle dark mode off and on in Safari, there are no issues and no need for JS.

You need to try it out with a wallet that has no manifest.json. Or you could remove the icons from that file (manifest.json) on the wallet and on the issuer to see what happens.

**Comment by dlongley** [comment]
@JoshDunnDev -- is it just me or does the background color for the modals still not match the native stuff?

**Comment by JoshDunnDev** [comment]
> @JoshDunnDev -- is it just me or does the background color for the modals still not match the native stuff?

I screenshotted the native stuff and color picked it so it should be the same.

**Comment by dlongley** [comment]
@JoshDunnDev,

If you clear your application data for your local authn.io instance and visit the wallet, it will bring up a permission modal for managing credentials. Highlighting the 'X' button there still uses the light mode background color.

**Comment by dlongley** [comment]
@JoshDunnDev, it seems like the separators (the horizontal lines below the modal header and above the "Remember..." checkbox) should be a lighter color (lighter than the background) rather than a darker one. You can barely see them.

**Comment by JoshDunnDev** [comment]
> @JoshDunnDev,
> 
> > I don't think this is needed because the CSS will understand the change. At least when I toggle dark mode off and on in Safari, there are no issues and no need for JS.
> 
> You need to try it out with a wallet that has no manifest.json. Or you could remove the icons from that file (manifest.json) on the wallet and on the issuer to see what happens.

Yes the colors of the default icons are correct when the veres images are not enabled.

**Comment by JoshDunnDev** [comment]
> @JoshDunnDev,
> 
> If you clear your application data for your local authn.io instance and visit the wallet, it will bring up a permission modal for managing credentials. Highlighting the 'X' button there still uses the light mode background color.

Fixed.

**Comment by JoshDunnDev** [comment]
> @JoshDunnDev, it seems like the separators (the horizontal lines below the modal header and above the "Remember..." checkbox) should be a lighter color (lighter than the background) rather than a darker one. You can barely see them.

Fixed.

**Pull request merged**
